version: '3.8'

services:

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    expose:
      - "6379"
    networks:
      rede_local:

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=petshop-system
      - POSTGRES_PASSWORD=test1234
      - POSTGRES_DB=petshop-system
    volumes:
      - /tmp/postgres-volume:/data/db
      - ./configuration/db/:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      rede_local:

#  petshop-api:
#    container_name: petshop-api
#    build: ../go/src/github.com/petshop-system/petshop-api/
#    restart: always
#    environment:
#      - REDIS_ADDR=redis:6379
#      - DB_USER=petshop-system
#      - DB_PASSWORD=test1234
#      - DB_NAME=petshop-system
#      - DB_HOST=postgres
#      - DB_PORT=5432
#      - DB_TYPE=postgres
#    ports:
#      - "5001:5001"
#    expose:
#      - "5001"
#    depends_on:
#      postgres:
#        condition: service_started
#      redis:
#        condition: service_started
#    networks:
#      rede_local:

#  petshop-api-gateway:
#    container_name: petshop-api-gateway
#    build: ../go/src/github.com/petshop-system/petshop-api-gateway
#    restart: always
#    ports:
#      - "9999:9999"
#    expose:
#      - "9999"
#    depends_on:
#      petshop-api:
#        condition: service_started
#      redis:
#        condition: service_started
#    networks:
#      rede_local:

networks:
  rede_local:
